### ISSUE TITLE
Ombutel integration

### ISSUE THREAD

**Issue by l3nz** [Loway/QueueMetrics-Espresso#2]

**Comment by mirkotp** [comment]
Espresso Failure 2017/05/29

---------------------

Distro: Ombutel v 1.0.22
Version: Asterisk 13.13.1
Download: https://www.ombutel.com/download-ombutel/
Options: Ombutel GUI
Notes: NA
Packages: asterisk:13.13.1;asterisk-core:13.13.1;qloaderd:1.32;queuemetrics:16.10.13;queuemetrics-espresso:0.18;

**Comment by fprior** [comment]
Just updated the name of new RPM from 0.2 to 0.20 to install the new RPM version that includes Ombutel.
