### ISSUE TITLE
Issabel integration

### ISSUE THREAD

**Issue by l3nz** [Loway/QueueMetrics-Espresso#3]

**Comment by KevinRavasi** [comment]
As for now QueueMetrics Espresso seems to works fine with Issabel's distro.
What should be done though is to create e particular case for Issabel's distributions, this is a list of packets that can be used to recognize an Issabel distribution.

issabel.noarch                            4.0.0-1                    issabel-base
elastix.noarch                            4.0.0-1                    @anaconda/4
asterisk.x86_64                           2009020507:11.25.0-0.el7.centos

DirectAMI seems to work with 17.06 but it's worth checking if there are any unnecessary dialplan modifications.

**Comment by fprior** [comment]
Queuemetrics-Espresso was updated to take in account Issabel Distribution 4.0
