### ISSUE TITLE
Issabel 4

### ISSUE THREAD

**Issue by mirkotp** [Loway/QueueMetrics-Espresso#6]
Distro: Issabel
Version: 4
Download: https://sourceforge.net/projects/issabelpbx/files/latest/download
Options:
Notes:
Packages: asterisk:11.25.0;queuemetrics:17.06.1;queuemetrics-espresso:0.20.0;

**Comment by fprior** [comment]
Queuemetrics-Espresso updated to include Issabel 4 as compatible distribution.
